# --backend-store-uri=postgresql+psycopg2://mlflow:mlflow@localhost:5432/mlflow
# export MLFLOW_TRACKING_URI=postgresql+psycopg2://mlflow:mlflow@localhost:5432/mlflow
# export MLFLOW_TRACKING_URI=postgresql+psycopg2://mlflow:mlflow@localhost:5432/mlflow

version: "3"
services:
  postgresql:
    image: postgres:10.5
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
