version: 2.1

jobs:
  build_doc:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout

      - run:
          name: Install Java
          command: |
            sudo apt-get update
            sudo apt-get install default-jdk -y
            sudo apt-get install maven -y
            java -version
      - run:
          name: Install Python dependencies
          environment:
            INSTALL_SMALL_PYTHON_DEPS: true
            INSTALL_LARGE_PYTHON_DEPS: true
          command: |
            ./travis/install-common-deps.sh
            pip install sphinx==2.2.1 sphinx-click==2.3.0

      - run:
          name: Build documentation
          command: |
            cd docs
            make rsthtml SPHINXOPTS="-W --keep-going"
            make javadocs

workflows:
  ci:
    jobs:
      - build_doc
