version: 2.1

jobs:
  build_doc:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout

      - run:
          name: Install Java
          command: |
            sudo apt update
            sudo apt install default-jdk -y
            sudo apt install maven -y
            java -version
      - run:
          name: Install Python dependencies
          environment:
            INSTALL_SMALL_PYTHON_DEPS: true
            INSTALL_LARGE_PYTHON_DEPS: true
          command: |
            pip install --progress-bar off -r ./travis/small-requirements.txt
            pip install --progress-bar off -r ./travis/large-requirements.txt
            pip install --progress-bar off .
            pip install --progress-bar off sphinx==2.2.1 sphinx-click==2.3.0

      - run:
          name: Build documentation
          command: |
            cd docs
            make javadocs

      - store_artifacts:
          path: docs/build/html

workflows:
  ci:
    jobs:
      - build_doc
