name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  xgboost:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Build
        run: |
          # https://xgboost.readthedocs.io/en/latest/build.html#building-on-linux-distributions
          git clone --recursive https://github.com/dmlc/xgboost
          cd xgboost
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)
