name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  xgboost:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Build
        run: |
          # https://xgboost.readthedocs.io/en/latest/build.html#building-on-linux-distributions
          git clone --recursive https://github.com/dmlc/xgboost
          cd xgboost/python-package
          python setup.py install

  pytorch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Enable conda
        run: |
          echo "/usr/share/miniconda/bin" >> $GITHUB_PATH

      - name: Build
        run: |
          # https://github.com/pytorch/pytorch#from-source

          conda install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions future six requests dataclasses
          conda install -c pytorch magma-cuda102

          git clone --recursive https://github.com/pytorch/pytorch
          cd pytorch
          # if you are updating an existing checkout
          git submodule sync
          git submodule update --init --recursive

          export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
          python setup.py install
